import React from 'react'
import { EmailLayout } from './EmailLayout/EmailLayout'
export const metadata = {
    title: 'Contacts',
    description: 'Generated by create next app',
}

const Contacts = () => {
    return (
        <div className='w-[95%] mx-auto'>
            <EmailLayout />
        </div>
    )
}

export default Contacts