import React from 'react'
export const metadata = {
    title: 'Contacts',
    description: 'Generated by create next app',
}

const Contacts = () => {
    return (
        <div>Contacts</div>
    )
}

export default Contacts