import React from 'react'
import WebsiteData from './DataTable/WebsiteData'

export const metadata = {
    title: 'Websites',
    description: 'Generated by create next app',
}

const Websites = () => {
    return (
        <div  className='container'>
            <WebsiteData />
        </div>
    )
}

export default Websites