import React from 'react'

export const metadata = {
    title: 'Websites',
    description: 'Generated by create next app',
}

const Websites = () => {
    return (
        <div>
            Websites
        </div>
    )
}

export default Websites