import React from 'react'
import UsersData from './DataTable/UsersData'

export const metadata = {
    title: 'Users',
    description: 'Generated by create next app',
}


const Users = () => {
    return (
        <section className='container'>
            <UsersData />
        </section>
    )
}

export default Users