import React from 'react'
import UsersData from './DataTable/UsersData'
import { EmailLayout } from '../contacts/EmailLayout/EmailLayout'

export const metadata = {
    title: 'Users',
    description: 'Generated by create next app',
}


const Users = () => {
    return (
        <section className='container'>
            {/* <UsersData /> */}
            {/* <EmailLayout /> */}
        </section>
    )
}

export default Users