
import React from 'react'
import LoginForm from './Form/LoginForm'
import logo from "@/public/stellar_logo.png"
// import loginImage from "@/public/login.png"
import Image from 'next/image'

export const metadata = {
    title: 'Login',
    description: 'Generated by create next app',
}



const Login = () => {
    return (
        <main className='min-h-[100vh] flex items-center loginForm bg-gradient-to-r from-green-300 to-green-500 '>
            <div className='w-[80%] mx-auto justify-between items-center     flex flex-wrap  '>
                {/* <div className='w-[5px] hidden lg:block bg-neutral-100 h-[300px] m-auto'></div> */}
                <div className='w-full h-[50%] lg:w-[30%] mt-5 bg-white border shadow-lg p-4 mx-auto rounded-lg'>
                    <div className='lg:mb-10 mb-5'>
                        <Image height={200} src={logo} width={200} alt='logo main' />
                    </div>
                    <div className='mb-4'>
                        <h4 className='text-xl font-semibold'>Login</h4>
                        <p className='text-sm font-light tracking-wider'>login using your email id and password</p>
                    </div>
                    <LoginForm />
                   
                </div>

            </div>
        </main>
    )
}

export default Login